# Указываем базовый образ
FROM node:13.12.0-alpine

# Укажем рабочую директорию
WORKDIR /usr/src/app

# Скопируем все package файлы в рабочую директорию
COPY package*.json ./

# Выполни установку всех зависимостей
RUN npm install

# Скопируем все из текущей директории в /usr/src/app
# Кроме того что описано в .dockerignore
COPY . .

# Сбилдим продакшн верисю фронтенд сервиса
# RUN npm run build

# Установим ГЛОБАЛЬНО пакет serve
# RUN npm install -g serve

## Здесь закомментируем и обьявим на уровне docker-compose
# Задекларируем порт 3000
# EXPOSE 3000

# Запустим приложение
# CMD ["node", "run start"]
